let xp = 10000
let heroi = "Alyn"

if(xp<=1000){
console.log("O heroi do nome " + heroi + " está no nivel FERRO")
}


if(xp>=1001 && xp<=2000){
    console.log("O heroi do nome " + heroi + "está no nivel BRONZE" )
    
    }
    
    if(xp>=2001 && xp<=5000){
        console.log("O heroi do nome" + heroi + "está no nivel PRATA")
    }
    if(xp>=5001 && xp<=7000){
        console.log("O heroi do nome " + heroi + " está no nivel OURO")
    }
    if(xp>=7001 && xp<=8000){
        console.log("O heroi do nome" + heroi + " está no nivel PLATINA")
    }
    if(xp>=8001 && xp<=9000){
        console.log("O heroi do nome " + heroi + " está no nivel DIAMANTE")
    }
    if(xp>=10000){
        console.log("O heroi do nome " + heroi + " está no nivel DESAFIANTE")
    }    